### ISSUE TITLE
Error install on redmine 4.1.0

### ISSUE THREAD

**Issue by aceccarelli** [florentsolt/redmine_wiki_templates#5]
Hi

Installing plugin on redmine 4.1.0 clean without plugin showed the error
Thanks!

redmine@Redmine:/var/www/redmine-4.1.0/plugins$ rails redmine:plugins:migrate RAILS_ENV=production
rails aborted!
NoMethodError: undefined method `alias_method_chain' for WikiController:Class
Did you mean?  alias_method
/var/www/redmine-4.1.0/plugins/redmine_wiki_templates/init.rb:41:in `block in included'
/var/www/redmine-4.1.0/plugins/redmine_wiki_templates/init.rb:40:in `class_eval'
/var/www/redmine-4.1.0/plugins/redmine_wiki_templates/init.rb:40:in `included'
/var/www/redmine-4.1.0/plugins/redmine_wiki_templates/init.rb:57:in `include'
/var/www/redmine-4.1.0/plugins/redmine_wiki_templates/init.rb:57:in `<top (required)>'
/var/www/redmine-4.1.0/lib/redmine/plugin.rb:181:in `block in load'
/var/www/redmine-4.1.0/lib/redmine/plugin.rb:172:in `each'
/var/www/redmine-4.1.0/lib/redmine/plugin.rb:172:in `load'
/var/www/redmine-4.1.0/config/initializers/30-redmine.rb:20:in `<top (required)>'
/var/www/redmine-4.1.0/config/environment.rb:16:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'

**Comment by florentsolt** [comment]
Sorry but this plugin is a dead project, I don't have time nor resources to fix it.
